language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="d27fc114-a20b-4c6e-840a-545ec60f5157"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - denfort50@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always